spring.application.name=demo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:53306/dbcourse
#spring.datasource.url=jdbc:mysql://localhost:53306/psy
spring.datasource.url=jdbc:mysql://localhost:53306/psy?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

